### ISSUE TITLE
email endpoint fails to deliver/send mails when sender using a gmail address

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#17]
As reported here: http://help.koken.me/customer/portal/questions/16188432-sending-emails-via-contactform

Tested on my own form that uses SMTP via gmail
![email_endpoints](https://cloud.githubusercontent.com/assets/11587201/13399743/13c97366-df05-11e5-9e64-27a80717c597.PNG)

First tested by sending a form from black.skorpio[a]gmail.com (Still not delivered)
After five minutes sent another form mail from bjarne[a]kokensupport.com (This was delivered immediately)

**Comment by MikeCostello** [comment]
Fixed in Email Endpoints v1.0.2 https://github.com/koken/koken/commit/06fb89e6d4bd1f208d10c02eb5e6059d7e544e71

**Comment by BlackSkorpio** [comment]
Issue is still present

Endpoint (v1.0.2) settings as above

**Fields present in form:**
- Name
- Email
- Message

**Steps to reproduce:**
Fill in fields as you should, and use a gmail.com address in the email field
